spring.application.name=dropship

spring.output.ansi.enabled=always

# Define os ambientes / properties ativas
spring.profiles.active=test
#spring.profiles.active=prod

app.jwt.secret=vbOgh2K0F9x+84gViyP+vzzpceaAoZRlMSmInSo7rrO1R+m/lmag/nq9j2Xo/tk74gEc0Ng5yeSUX9TAreNnYA==

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE