spring.application.name=dropship

spring.output.ansi.enabled=always

# Define os ambientes / properties ativas
spring.profiles.active=test
#spring.profiles.active=prod

app.jwt.secret=vbOgh2K0F9x+84gViyP+vzzpceaAoZRlMSmInSo7rrO1R+m/lmag/nq9j2Xo/tk74gEc0Ng5yeSUX9TAreNnYA==