# Configuração de Base de Dados
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/center_db
spring.datasource.username=root
spring.datasource.password=1234

# Show SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false

# Debug Options
debug=false
spring.mvc.log-request-details=true
logging.level.org.springframework=debug
logging.level.org.springframework.security=trace

